# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Engine-waitingTime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Engine-waitingTime.proto',
  package='com.WaitingTimeServer.grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x45ngine-waitingTime.proto\x12\x1a\x63om.WaitingTimeServer.grpc\"\x11\n\x0fRegistryRequest\"#\n\x10RegistryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2x\n\x0fRegistryService\x12\x65\n\x08Registry\x12+.com.WaitingTimeServer.grpc.RegistryRequest\x1a,.com.WaitingTimeServer.grpc.RegistryResponseb\x06proto3'
)




_REGISTRYREQUEST = _descriptor.Descriptor(
  name='RegistryRequest',
  full_name='com.WaitingTimeServer.grpc.RegistryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=73,
)


_REGISTRYRESPONSE = _descriptor.Descriptor(
  name='RegistryResponse',
  full_name='com.WaitingTimeServer.grpc.RegistryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.WaitingTimeServer.grpc.RegistryResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['RegistryRequest'] = _REGISTRYREQUEST
DESCRIPTOR.message_types_by_name['RegistryResponse'] = _REGISTRYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegistryRequest = _reflection.GeneratedProtocolMessageType('RegistryRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRYREQUEST,
  '__module__' : 'Engine_waitingTime_pb2'
  # @@protoc_insertion_point(class_scope:com.WaitingTimeServer.grpc.RegistryRequest)
  })
_sym_db.RegisterMessage(RegistryRequest)

RegistryResponse = _reflection.GeneratedProtocolMessageType('RegistryResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRYRESPONSE,
  '__module__' : 'Engine_waitingTime_pb2'
  # @@protoc_insertion_point(class_scope:com.WaitingTimeServer.grpc.RegistryResponse)
  })
_sym_db.RegisterMessage(RegistryResponse)



_REGISTRYSERVICE = _descriptor.ServiceDescriptor(
  name='RegistryService',
  full_name='com.WaitingTimeServer.grpc.RegistryService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=112,
  serialized_end=232,
  methods=[
  _descriptor.MethodDescriptor(
    name='Registry',
    full_name='com.WaitingTimeServer.grpc.RegistryService.Registry',
    index=0,
    containing_service=None,
    input_type=_REGISTRYREQUEST,
    output_type=_REGISTRYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTRYSERVICE)

DESCRIPTOR.services_by_name['RegistryService'] = _REGISTRYSERVICE

# @@protoc_insertion_point(module_scope)
